export type Product = {
  slug: string
  name: string
  type: string
  category: string
  short: string
  price: number
  compareAt?: number
  rating: number
  reviews: number
  badge?: string
  image: string
  accent?: string
  integrations?: string[]
  plan?: "Lifetime" | "Subscription" | "One-time"
  status?: "new" | "hot" | "ending"
  priceRange?: "under-50" | "50-100" | "100-plus"
}

export const products: Product[] = [
  {
    slug: "grigora",
    name: "Grigora",
    type: "Web builders",
    category: "Software",
    short: "Create websites, blogs, and online stores with a drag‑and‑drop builder and built‑in SEO tools.",
    price: 59,
    compareAt: 299,
    rating: 5.0,
    reviews: 42,
    badge: "ADOPLE AI SELECT",
    image: "/web-builder-interface-purple-gradient.png",
    accent: "from-indigo-600 to-violet-600",
    integrations: ["WordPress", "Zapier"],
    plan: "Lifetime",
    status: "hot",
    priceRange: "50-100",
  },
  {
    slug: "jodian",
    name: "Jodian",
    type: "AI Video",
    category: "Software",
    short: "Create studio‑quality videos with interactive forms, polls, and on‑brand scenes powered by AI.",
    price: 69,
    compareAt: 516,
    rating: 4.9,
    reviews: 73,
    badge: "ADOPLE AI SELECT",
    image: "/ai-platform-interface-blue-gradient.png",
    accent: "from-sky-500 to-indigo-600",
    integrations: ["OpenAI", "Zapier"],
    plan: "Subscription",
    status: "new",
    priceRange: "50-100",
  },
  {
    slug: "restreamer",
    name: "Restreamer",
    type: "Lead generation",
    category: "Software",
    short: "Unleash new marketing strategies and scroll‑stopping creative assets with an AI ad generator.",
    price: 39,
    compareAt: 468,
    rating: 4.8,
    reviews: 156,
    badge: "ADOPLE AI SELECT",
    image: "/streaming-software-interface-dark-purple.png",
    accent: "from-purple-600 to-fuchsia-500",
    integrations: ["Meta Ads", "Google Ads"],
    plan: "Lifetime",
    status: "ending",
    priceRange: "under-50",
  },
  // {
  //   slug: "fluent-3d",
  //   name: "Fluent 3D",
  //   type: "Web builders",
  //   category: "Software",
  //   short: "Build WordPress sites fast with a powerful set of blocks, templates, and 3D‑friendly sections.",
  //   price: 49,
  //   compareAt: 588,
  //   rating: 4.7,
  //   reviews: 89,
  //   badge: "ADOPLE AI SELECT",
  //   image: "/web-design-tool-interface-blue-gradient.png",
  //   accent: "from-blue-600 to-cyan-500",
  //   integrations: ["WordPress"],
  //   plan: "One-time",
  //   status: "hot",
  //   priceRange: "under-50",
  // },
  // {
  //   slug: "beyond",
  //   name: "Beyond",
  //   type: "Crypto",
  //   category: "Software",
  //   short: "AI‑powered insights for smarter crypto investments and automated research workflows.",
  //   price: 59,
  //   compareAt: 348,
  //   rating: 4.6,
  //   reviews: 31,
  //   badge: "ADOPLE AI SELECT",
  //   image: "/software-dashboard-interface.png",
  //   accent: "from-emerald-600 to-teal-500",
  //   integrations: ["Slack"],
  //   plan: "Subscription",
  //   status: "new",
  //   priceRange: "50-100",
  // },
  // {
  //   slug: "senuto",
  //   name: "Senuto",
  //   type: "Customer support",
  //   category: "Software",
  //   short: "Deploy customer‑trained AI agents to engage visitors, qualify leads, and automate workflows.",
  //   price: 69,
  //   compareAt: 240,
  //   rating: 4.8,
  //   reviews: 117,
  //   badge: "ADOPLE AI SELECT",
  //   image: "/analytics-dashboard.png",
  //   accent: "from-rose-600 to-orange-500",
  //   integrations: ["Zendesk", "Slack"],
  //   plan: "Lifetime",
  //   status: "hot",
  //   priceRange: "50-100",
  // },
  // {
  //   slug: "lumical",
  //   name: "Lumical",
  //   type: "Calendar & scheduling",
  //   category: "Software",
  //   short: "Beautiful scheduling pages, round‑robin availability, and advanced booking automation.",
  //   price: 59,
  //   compareAt: 360,
  //   rating: 4.7,
  //   reviews: 94,
  //   badge: "ADOPLE AI SELECT",
  //   image: "/project-management-tool.png",
  //   accent: "from-indigo-600 to-blue-500",
  //   integrations: ["Google Calendar"],
  //   plan: "Lifetime",
  //   status: "new",
  //   priceRange: "50-100",
  // },
  // {
  //   slug: "sendr",
  //   name: "Sendr",
  //   type: "Lead generation",
  //   category: "Software",
  //   short: "Turn contact data into personalized pages and dynamic video messages that convert.",
  //   price: 79,
  //   compareAt: 588,
  //   rating: 4.9,
  //   reviews: 23,
  //   badge: "ADOPLE AI SELECT",
  //   image: "/design-software-interface.png",
  //   accent: "from-amber-500 to-orange-500",
  //   integrations: ["HubSpot", "Zapier"],
  //   plan: "Subscription",
  //   status: "hot",
  //   priceRange: "100-plus",
  // },
  // {
  //   slug: "wizetool",
  //   name: "WizeTool",
  //   type: "WhatsApp",
  //   category: "Software",
  //   short: "Automate WhatsApp campaigns with templates, flows, and smart routing that scales.",
  //   price: 69,
  //   compareAt: 240,
  //   rating: 4.6,
  //   reviews: 52,
  //   badge: "ADOPLE AI SELECT",
  //   image: "/web-builder-interface-purple-gradient.png",
  //   accent: "from-green-600 to-emerald-500",
  //   integrations: ["WhatsApp", "Zapier"],
  //   plan: "Lifetime",
  //   status: "new",
  //   priceRange: "50-100",
  // },
  // {
  //   slug: "clickgiant",
  //   name: "ClickGiant",
  //   type: "SEO",
  //   category: "Software",
  //   short: "Effortless SEO automation to boost rankings without plugins or technical headaches.",
  //   price: 79,
  //   compareAt: 600,
  //   rating: 4.8,
  //   reviews: 67,
  //   badge: "ADOPLE AI SELECT",
  //   image: "/ai-platform-interface-blue-gradient.png",
  //   accent: "from-lime-600 to-emerald-500",
  //   integrations: ["WordPress", "Webflow"],
  //   plan: "Subscription",
  //   status: "ending",
  //   priceRange: "100-plus",
  // },
  // {
  //   slug: "playzo",
  //   name: "Playzo",
  //   type: "Content marketing",
  //   category: "Software",
  //   short: "Create quizzes and games to capture leads, drive sales, and enhance learning.",
  //   price: 69,
  //   compareAt: 828,
  //   rating: 4.7,
  //   reviews: 45,
  //   badge: "ADOPLE AI SELECT",
  //   image: "/streaming-software-interface-dark-purple.png",
  //   accent: "from-pink-600 to-rose-500",
  //   integrations: ["Webflow", "Zapier"],
  //   plan: "Lifetime",
  //   status: "hot",
  //   priceRange: "50-100",
  // },
  // {
  //   slug: "aitest-ai",
  //   name: "AiTest.ai",
  //   type: "SEO",
  //   category: "Software",
  //   short: "Automated QA for images to improve your site’s SEO, accessibility, and performance.",
  //   price: 69,
  //   compareAt: 360,
  //   rating: 4.9,
  //   reviews: 38,
  //   badge: "ADOPLE AI SELECT",
  //   image: "/web-design-tool-interface-blue-gradient.png",
  //   accent: "from-slate-600 to-gray-500",
  //   integrations: ["OpenAI", "Slack"],
  //   plan: "One-time",
  //   status: "new",
  //   priceRange: "50-100",
  // },
]
